---
apiVersion: v1
kind: Service
metadata:
  name: ordersmanagement
  labels:
    app: ordersmanagement
spec:
  type: ClusterIP
  selector:
    app: ordersmanagement
  ports:
  - protocol: TCP
    port: 8020
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: ordersmanagement
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: ordersmanagement
    spec:
      containers:
      - name: ordersmanagement
        image: mnemonika/test:ordersmanagement
        imagePullPolicy: Always
        ports:
        - containerPort: 8020
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8020
          timeoutSeconds: 1
