---
apiVersion: v1
kind: Service
metadata:
  name: ordersmanagement
  labels:
    app: ordersmanagement
spec:
  type: ClusterIP
  selector:
    app: ordersmanagement
  ports:
  - protocol: TCP
    port: 8020
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: ordersmanagement
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: ordersmanagement
    spec:
      containers:
      - name: ordersmanagement
        image: mnemonika/test:ordersmanagement
        imagePullPolicy: Always
        ports:
        - containerPort: 8020
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8020
          timeoutSeconds: 1
        env:
          - name: POSTGRES_HOST
            value: postgres
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: postgres
                key: database-name
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres
                key: database-user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres
                key: database-password
          - name: ConnectionStrings__PostgresqlConnection
            value: "Username=$(POSTGRES_USER);Password=$(POSTGRES_PASSWORD);Host=$(POSTGRES_HOST);Port=5432;Database=$(POSTGRES_DB)"
